### ISSUE TITLE
Fixtures

### ISSUE THREAD

**Issue by Fanny42** [PointPlusYt/Buandier#2]
D'après https://github.com/EasyCorp/EasyAdminBundle/issues/1989, on peut résoudre ton bug de fixtures en passant les noms de méthodes add/removeClothe~s~ au singulier.
J'ai testé, ça fonctionne, mais pas les droits suffisants sur le repo pour pusher ma branche et faire une PR :sweat_smile:

**Comment by jorisre** [comment]
👋🏻  @Fanny42 
Pour contribuer à un projet il faut le _"forker"_
![Screen Shot 2020-11-19 at 18 14 22](https://user-images.githubusercontent.com/7545547/99700105-0d804000-2a93-11eb-88eb-4749b56c8ed2.png)

C'est assez simple et tout est décrit ici https://guides.github.com/activities/forking/

Bonne contribution :)

**Comment by Djyp** [comment]
> Djyp added a commit that referenced this issue 3 hours ago
Live #2 su 06/12/20

Mouais, ou pas, j'ai juste écrit `#2` mais Github pense que je parle de lui, il se prend pour le centre du monde

**Comment by Djyp** [comment]
C'est corrigé ! Merci @Fanny42 ! Ça marche très bien !

https://github.com/PointPlusYt/Buandier/commit/a532f23df45e54772aaa00a0eb51831ad1084ab2

C'est d'ailleurs pas bien logique que soit les fixtures n'utilisent pas les bons noms de méthodes, soit le maker ne crée pas les bons noms de méthodes…
